#ifndef ENUMS_H
#define ENUMS_H
enum Rank {TWO = 2, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING, ACE};
enum Suit {CLUB = 1, DIAMOND, HEART, SPADE};
enum Round {DEAL = 0, FLOP, TURN, RIVER};
enum Hand {HIGH, PAIR, TWOPAIR, THREEOFAKIND, STRAIGHT, FLUSH, FULLHOUSE, FOUROFAKIND, STRAIGHTFLUSH, ROYALFLUSH};
enum DecisionType {FOLDORNOT = 0, FOLDORCALL, CALLORRAISE, CHECKORRAISE};
enum WeightType {LEFT = 0, RIGHT};
#endif